### ISSUE TITLE
Start animator visualiser from the main thread

### ISSUE THREAD

**Issue by m-sz** [mrozycki/rustmas#40]
Currently the visualiser is started from a separate thread created by tokio::spawn. In order for the visualisation subsystem to acquire the necessary graphics context and window handles it is best to start it from the main thread instead, to avoid compatibility problems.

**Comment by mrozycki** [comment]
We decided that the Bevy visualizer will not be started by animator, like the old visualizer currently is. Instead, it will be a separate application, subscribing to a websocket endpoint in webapi to fetch new frames of animation. Therefore this ticket is no longer applicable.
